### ISSUE TITLE
[Feature Request] 'Select All' - Option in Contact Requests list

### ISSUE THREAD

**Issue by Rubylion** [deltachat/deltachat-android-ii#161] opened 2018-12-05 22:22 UTC
I had to delete over 200 Mails, that had been saved in the Conract Requests Tab. Selecting every single one sololy. A 'select all' option would really improve the handling

**Comment by r10s** [comment] 2018-12-06 00:10
hi, @Rubylion thank you for your post.

in general, however, it is better to discuss feature requests with a broader audience in the forum at https://support.delta.chat

**Comment by angelo-fuchs** [comment] 2018-12-06 11:36
@Rubylion Where did that mails come from? Was that SPAM? Or were that regular E-Mails that you just didn't want in your Deltachat?

**Comment by r10s** [comment] 2018-12-06 13:00
there is also the rough idea of limiting the retained history in general which could also affect the contact requests then, see https://github.com/deltachat/deltachat-core/issues/244

**Comment by Rubylion** [comment] 2018-12-06 17:51
@angelo-fuchs These were regular mails, I already deleted from my inbox. Obviously DeltaChat saved those under contact requests

**Comment by r10s** [comment] 2018-12-07 14:12
@Rubylion thank you for coming back to this. that regular mails are shown in the contact requests, is by design currently.

as mentioned above there are ideas to improve handling of this in the core, https://github.com/deltachat/deltachat-core/issues/244

as it's more a core-issue and is not really related to android-dev, i would suggest to continue the discussion there or in the forum and close this issue here.

**Closed** 2018-12-07 14:13 UTC
Labels: feature proposal

**Comment by testbird** [comment] 2018-12-10 14:38
The "limit retained history" approach is not the correct one for the incoming emails list (wrongly called "contact requests"). 

The incoming emails situation would be solved better with the "syncing" approach, i.e. auto-delete messages locally if deleted on the server (through other clients), and if deleting a message in the incoming emails (e.g. spam) also delete it from the server. Before doing this, of course the naming of the "contact requests" should be corrected, to proper indicate what is being listed.

After deltachat's "incoming emails" view is synced with the INBOX, there could be an option to "limit the retained history", but it may be more appropriate to leave that to be handled by classic email clients or server filters.
