### ISSUE TITLE
Endless loop when enebling screen lock option

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-android-ii#181] opened 2018-12-19 15:32 UTC
The app get stuck in an endless loop (you must reinstall the app to be able to use it again) if you enable the screen lock option. I have a set a pattern to unlock my phone, I don't know if with a PIN lock this also happens but it is highly probably.
This seems to be the same that #112 

- Platform (android/blackberry/anbox): Android 6.0
- Device: BLU
- Delta Chat Version: 0.91
- Expected behavior: I can enable the screen lock option and use my system pattern to unlock it
- Actual behavior: DC get stuck in an infinite loop if I enable the screen lock option: DC keep asking me to enter the pattern over and over, if I close the app, and open it again, the screen lock is shown, and if enter it it once again get stuck in this infinite loop, if I enter the pattern wrong the proper message is shown, if I enter the pattern right the same lock screen is shown again.
- Steps to reproduce the problem: Go to settings and enable the screen lock option, done! you screwed your Delta Chat app, reinstall.

**Comment by r10s** [comment] 2018-12-19 15:51
@adbenitez thanks for reporting :+1: 

@Boehrsi maybe you can have a look at this?

**Comment by r10s** [comment] 2018-12-20 01:31
i could not reproduce the bug on my test devices (both android 7.1)
maybe it is related to the android version.

as a workaround, however, it should work to disable the pattern in the system settings.

**Comment by adbenitez** [comment] 2018-12-20 14:17
Yeah thanks for that, I would have saved some money if I had know that before... instead of reinstalling and re-downloading all chats and conversations :(

**Comment by Boehrsi** [comment] 2018-12-20 18:37
@adbenitez sorry to hear that you had to setup everything again. I don't think this is related to #112 as that was just a missing line of code, which should now work as intended. I will have a look tomorrow and hope I can figure out what exactly the problem is.
I think @r10s is right and this is related to the Android version used in that case. I will try to setup an emulator which matches the version to get an idea why this happens.

**Comment by adbenitez** [comment] 2018-12-20 21:39
Boehrsi sorry, I meant I am having the same issue, not that it is caused by the same error on code, my fault not elaborate that properly. Thanks for taking care of this.

**Comment by r10s** [comment] 2018-12-20 21:47
@Boehrsi +1

**Comment by Boehrsi** [comment] 2018-12-21 13:15
Should be fixed now. Was a pretty strange behavior only happening on Android 6.0.0 (on 6.0.1 it's already fixed), so I think it's more or less an Android bug. But I worked around it.
Tested with 6.0.0, 6.0.1 and 9.0.0 and it seems to work everywhere now.

**Comment by r10s** [comment] 2019-01-03 12:39
works for me and also @adbenitez has added a "heart", so i think we can close this :)
@Boehrsi @adbenitez happy new year, btw :)

**Closed by r10s** 2019-01-03 12:39 UTC
Labels: bug

**Comment by adbenitez** [comment] 2019-01-08 22:55
@r10s never received this message in DC, happy new year for you
