### ISSUE TITLE
Creating Backup doesn't work on older phones

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/deltachat-android-ii#208] opened 2019-01-07 11:32 UTC
The code requires API Level 21 and just crashes the App on lower versions, while suppressing linter messages.

https://github.com/deltachat/deltachat-android-ii/blob/master/src/org/thoughtcrime/securesms/util/ScreenLockUtil.java#L29

calls https://developer.android.com/reference/android/app/KeyguardManager#createConfirmDeviceCredentialIntent(java.lang.CharSequence,%20java.lang.CharSequence)

which has been added in API Level 21. There is no check for earlier versions.

The proper code should probably look like this (can't test atm):

```
// Notice the lack of @TargetAPI in this line.
    public static boolean applyScreenLock(Activity activity, int requestCode) {
        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            KeyguardManager keyguardManager = (KeyguardManager) activity.getSystemService(Context.KEYGUARD_SERVICE);
            Intent intent;
            if (keyguardManager != null) {
                intent = keyguardManager.createConfirmDeviceCredentialIntent(activity.getString(R.string.security_authentication_unlock_title), activity.getString(R.string.security_authentication_unlock_description));
                if (intent != null) {
                    activity.startActivityForResult(intent, requestCode);
                    return true;
                }
            }
        }
        return false;
    }
```

**Comment by r10s** [comment] 2019-01-07 11:38
cc @Boehrsi

**Comment by Boehrsi** [comment] 2019-01-07 12:33
Argh I missed that one. I will fix it tomorrow (disable the request as mentioned) and will have a look regarding the other createConfirmDeviceCredentialIntent calls to verify no similar problems exist.

**Comment by r10s** [comment] 2019-01-07 12:35
@Boehrsi cool :)

**Comment by Boehrsi** [comment] 2019-01-07 12:35
Btw. Happy New Year @r10s and @angelo-fuchs :)

**Comment by r10s** [comment] 2019-01-07 12:47
yeah, happy new year @Boehrsi @angelo-fuchs 🎆 🎇 🍾

**Comment by Boehrsi** [comment] 2019-01-07 12:52
Should work now as intended.

**Comment by r10s** [comment] 2019-01-08 21:06
closing this for now, @angelo-fuchs feel free to re-open if there are still problems :)

**Closed by r10s** 2019-01-08 21:06 UTC
Labels: bug

**Comment by angelo-fuchs** [comment] 2019-01-15 09:19
@Boehrsi Don't know if related: When I start Backup and wait until about 5% and then hit 'Cancel' I see an SQL Exception.

But the initial bug is gone, so maybe this should be a new issue.

**Comment by r10s** [comment] 2019-01-15 11:33
i think, this comes from the core, seems to be a more or less expected error when the database is switched, however, i did not investigate too much in that.
maybe we should also not expose sql-errors to the ui. but that's also a core-thingie.
