### ISSUE TITLE
flaky message sending

### ISSUE THREAD

**Issue by testbird** [deltachat/deltachat-android-ii#130] opened 2018-11-19 17:38 UTC
Sending a message while the router is not connected to the internet causes sending delays long after the connection is back on.

I guess what happens is that many times the random delay is shorter than the time passed since job creation, until at one time it shoots to many minutes or even hours.

Here again the summary for continuously and deterministically ensuring that messages are
* sent as soon as possible, but battery saving starts to set in after a while as
* attempts are reduced with 3.33 minute timeouts, if traveling weak flaky networks,
* and 10 minutes timeouts, if the network connection is stable (possibly longer lasting server/routing problems).
* While a new local network connection (wifi) and dc_maybe_network() also causes **all** messages to be sent immediately.

To limit traffic:
* Permanent errors from the smtp server should cancel the job immediately (Looks as if message size and space errors are already catched.)
* It should be possible to continue interrupted transmissions. (I don't know if that's supported.)

To send ASAP and save battery: 
* Do rather quick retries to process all jobs (a pass goes through all of them in the order of creation, failing individual jobs). With simple delays between the passes only up to max. 7 seconds between retries (non-randomized).
* Every pass starts with the oldest message, but goes on trying later messages if one message fails.
* Message jobs may be canceled after being in the loop for a some amount of time.
* Count the number of uncompleted passes with a "circuit breaker" that interrupts ("opens") the retry loop for longer periods (e.g. from 6 up to 10 fails => 30 seconds,  up to 14 => 1 minute, up to 20 => 5 minutes, and 10 minutes beyond 20 fails)
* When the circuit is "open" (waiting), block any newly active online status (volatile weak flaky network connection) from triggering an immediate retry, only allow a single retry (pass) after the circuit breaker has already waited for 1/3 of the current timeout ("half-open" circuit state).

See https://dzone.com/articles/understanding-retry-pattern-with-exponential-backover

**Comment by r10s** [comment] 2018-11-19 17:41
this is fixed with the version currently in development.

**Closed** 2018-11-19 17:43 UTC

**Comment by testbird** [comment] 2018-11-20 15:03
I filed this issue, because, as stated, the new exponential backoff delays random messages for very long random periods (long after the router's connection is back online). 

I see you've edited and completely deleted your first comment, which was originally claiming the issue is beeing solved in the current development version, whereas the truth is, the problem has only been introduced with the "*randomized* exponential backoff" into the current code.

Before, I had only commented on the unfortunate code changes in the *closed* pull requests, in an attempting to make you aware and discuss the problems, researching a proper solution, and including your remarks in the solution. I couldn't see much consideration in your response.

But what is counting more is the track record of the deltachat (Email-chat) code developments, it is unfortunately not positive currently, and hardly will if you guys continue reacting in a way that looks pretty side-focused, and keep closing issues without solving anything like you do.

**Comment by r10s** [comment] 2018-11-20 15:20
i modified my post mainly to adapt my tone.

**Comment by r10s** [comment] 2018-11-20 15:24
apart, from that, yes, the problem is targeted in the current development version, and i wrote that, but i just thought that this does not really matter here.

**Comment by testbird** [comment] 2018-11-20 16:02
How strange that you think pointing to or explaining your solution would not matter.

Well, scheduling complete passes according to the number of failed passes as sketched above shouldn't be too hard, maybe you're considering it.

**Comment by r10s** [comment] 2018-11-20 20:06
there are of comments referring to your ideas in the pr.

btw. have you ever _tried_ the exponential backoff before commenting on it?

**Comment by testbird** [comment] 2018-11-21 12:02
What I am missing is any hint that you recognize the issue with the per message *random* exponential backoff in general, and especially if the implementation causes half of the random values always beeing in the past (immediate retry and exponential growth of the potential for the next delay).

* shuffled messages
* sending not resumed quickly after a problem wihin the network is gone
* hours without any retries
* likely not much battery saving compared to 10 minute retry intervals (small consumption difference, battery is emty in a couple of days anyway)


That's really unfortunate, because without some sort of insight or planning shown, it only leaves to suspect that either the code was not fully understood and/or there is no interested in a solution, and no willingness to further explain, ask and talk in order to come to a better understanding and solution.

There is one on-topic comment showing technical competence that is not mixing up timeouts and keep-alives, it's from you.

Sadly..
> no response to the notion that letting each pass try all queued messages (as summarized above in this issue) should usually solve intermittent  transfer errors in a less disturbing way (i.e. without letting every  connection problem randomly mix up the message order by default and  introducing long random per message delays).

Nevertheless, such message delays and shuffling will clearly be disturbing for users, short network outages may falsely get associated different things like separate accounts, like here.
https://lists.codespeak.net/hyperkitty/list/delta@codespeak.net/thread/3P5INWTATO7UWCIO3X5MW2O4ACAEIRTR/ 
So it really does not look like a good idea to me to have the backoff algorithm do shuffling when users expect messages to be transferred as soon and accountable as possible. Therefore I filed an issue to track this systematic problem.

**Comment by angelo-fuchs** [comment] 2018-11-21 12:10
@testbird I get the impression that it would be easier to talk about this in a more direct and personal way, could you send me an email? af@steamnet.de

**Comment by testbird** [comment] 2018-11-24 16:33
Thanks, but no, I'd prefer public exchange about implications and improvements of technical details and  straight answers, above personal emailing or some "data instead of dialogue" (from "Who needs democracy when you have data?").

**Comment by testbird** [comment] 2018-12-11 10:47
Now I could better identify the error I experienced, it wasn't the router itself but its IP. The email provider blacklists IPs and returns error messages. That made the connection fail on on a mobile network (that uses NAT) while it worked when connected with another network.

I only noticed this after trying to use webmail on the phone while having the problem in the mobile network, because this produced a proper notice about the remaining hours of the blacklisting.

Please consider some small adaptions for the current get_backoff_time_offset() to make it work "as soon as possible" (or rather sensible with the delays), as also linked from above: https://github.com/deltachat/deltachat-core/pull/446#issuecomment-441385285
